id: P002953
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5539
  title: ཁམས་སྡེ་དགེ་རྒྱལ་པོའི་སྲིད་དོན་ལོ་རྒྱུས་
  author: ''
  volumes:
    ae2574de87864b22aced0f7aecf43cfd:
      image_group_id: I1KG5551
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
