id: IA9FB88A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:20:48+00:00'
last_modified: '2022-06-07T16:31:45.851530+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5539
  title: ཁམས་སྡེ་དགེ་རྒྱལ་པོའི་སྲིད་དོན་ལོ་རྒྱུས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '3661':
      image_group_id: I1KG5551
      title: ''
      total_pages: 324
      order: 1
      base_file: 3661.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
